"""Reusable utilities for 2-D labeled tissue segmentation images."""

from .adjacency import (
    adjacency_from_labels,
    adjacency_pairs_from_labels,
    adjacency_with_contact_from_labels,
    adjacency_with_unique_from_labels,
    border_labels,
    centroids_from_labels,
    get_centroids,
    graph_from_labels,
    label_is_border,
    label_pixel_counts,
)
from .coloring import (
    apply_color_lut_int,
    color_planar_with_variety,
    dsatur_color,
    rebalance_K_colors,
    refine_to_K_colors,
    show_map_with_colors,
)
from .contours import ordered_contour_from_mask, ordered_contours_from_labels
from .io import (
    load_img,
    load_label_graph,
    load_label_image,
    save_img,
    save_label_graph,
    save_label_graph_from_labels,
    save_label_image,
)
from .junctions import (
    Junction,
    cluster_junctions_with_labels,
    junction_pixels_with_labels,
    junctions_from_labels,
    merge_close_junctions,
)
from .plotting import (
    draw_graph,
    label_map,
    plot_adjacency_graph,
    plot_contours,
    plot_junctions,
    plot_label_boundaries,
    plot_label_image,
)
from .preprocessing import (
    crop_to_foreground_bbox,
    dialate_labels,
    dilate_labels,
    erode_labels,
    fill_internal_gaps_edt,
    find_non_self_connected_labels,
    load_image_pipeline,
    remove_non_self_connected_bits,
    replace_labels,
    shuffle_labels,
    skeletonize_dilate,
    skeletonize_erode,
    skeletonize_labels,
)
from .validation import unique_labels, validate_label_image

__all__ = [
    "Junction",
    "adjacency_from_labels",
    "adjacency_pairs_from_labels",
    "adjacency_with_contact_from_labels",
    "adjacency_with_unique_from_labels",
    "apply_color_lut_int",
    "border_labels",
    "centroids_from_labels",
    "cluster_junctions_with_labels",
    "color_planar_with_variety",
    "crop_to_foreground_bbox",
    "dialate_labels",
    "dilate_labels",
    "draw_graph",
    "dsatur_color",
    "erode_labels",
    "fill_internal_gaps_edt",
    "find_non_self_connected_labels",
    "get_centroids",
    "graph_from_labels",
    "junction_pixels_with_labels",
    "junctions_from_labels",
    "label_is_border",
    "label_pixel_counts",
    "label_map",
    "load_image_pipeline",
    "load_img",
    "load_label_graph",
    "load_label_image",
    "merge_close_junctions",
    "ordered_contour_from_mask",
    "ordered_contours_from_labels",
    "plot_adjacency_graph",
    "plot_contours",
    "plot_junctions",
    "plot_label_boundaries",
    "plot_label_image",
    "rebalance_K_colors",
    "refine_to_K_colors",
    "replace_labels",
    "remove_non_self_connected_bits",
    "save_label_graph",
    "save_label_graph_from_labels",
    "save_img",
    "save_label_image",
    "show_map_with_colors",
    "shuffle_labels",
    "skeletonize_dilate",
    "skeletonize_erode",
    "skeletonize_labels",
    "unique_labels",
    "validate_label_image",
]
